---
- name: Wordpress install packages
  apt:
    name: "{{ wordpress__default_packages }}"
    update_cache: yes
    state: present
  when: wordpress__install

- name: MySQL/MariaDB install packages
  apt:
    name: "{{ wordpress__db_packages }}"
    update_cache: yes
    state: present
  when: wordpress__install

- name: Single conf tasks
  include_tasks: singleconf.yml
  when:
    - wordpress__install
    - wordpress__configure
    - wordpress__conf|type_debug == "dict"
  
- name: Multiple conf tasks
  include_tasks: multiconf.yml
  with_items: "{{ wordpress__conf }}"
  when:
    - wordpress__install
    - wordpress__configure
    - wordpress__conf|type_debug == "list"

- name: Create wordpress content link file
  file:
    path: "/var/www/wordpress"
    src: "/usr/share/wordpress"
    state: link
  notify: Reload apache2 service
  when:
    - wordpress__install
    - wordpress__configure

- name: Create wordpress htaccess file
  template:
    src: htaccess
    dest: "/etc/wordpress/htaccess"
  when:
    - wordpress__install
    - wordpress__configure

- name: Activate apache2 rewrite module
  apache2_module:
    ignore_configcheck: yes
    name: rewrite
    state: present
  notify: Reload apache2 service
  ignore_errors: True
  when:
    - wordpress__install
    - wordpress__configure

- name: Activate apache2 ssl module (single conf)
  apache2_module:
    ignore_configcheck: yes
    name: ssl
    state: present
  notify: Reload apache2 service
  ignore_errors: True
  when:
    - wordpress__install
    - wordpress__configure
    - wordpress__conf|type_debug == "dict"
    - wordpress__conf.use_ssl

- name: Activate apache2 ssl module (multi conf)
  with_items: "{{ wordpress__conf }}"
  apache2_module:
    ignore_configcheck: yes
    name: ssl
    state: present
  notify: Reload apache2 service
  ignore_errors: True
  when:
    - wordpress__install
    - wordpress__configure
    - wordpress__conf|type_debug == "list"
    - item.use_ssl
