---
- name: MySQL/MariaDB user create
  mysql_user:
    name: "{{ item.db_user }}"
    password: "{{ item.db_password }}"
    priv: "{{ item.db_name }}.*:ALL,GRANT"
    host: "%"
    login_user: "{{ item.db_admin_user }}"
    login_password: "{{ item.db_admin_password }}"
    login_host: "{{ item.db_host }}"

- name: MySQL/MariaDB db create
  mysql_db:
    name: "{{ item.db_name }}"
    login_user: "{{ item.db_admin_user }}"
    login_password: "{{ item.db_admin_password }}"
    login_host: "{{ item.db_host }}"

- name: Create apache service file
  template:
    src: multi_vhost.conf
    dest: "/etc/apache2/sites-available/{{ item.hostname }}"
  notify: Reload apache2 service

- name: Create apache2 link service file
  file:
    path: "/etc/apache2/sites-enabled/{{ item.hostname }}.conf"
    src: "/etc/apache2/sites-available/{{ item.hostname }}"
    state: link
  notify: Reload apache2 service

- name: Create wordpress config file
  template:
    src: multi_config-site.conf
    dest: "/etc/wordpress/config-{{ item.hostname }}.php"
