---
- name: MySQL/MariaDB user create
  mysql_user:
    name: "{{ wordpress__conf.db_user }}"
    password: "{{ wordpress__conf.db_password }}"
    priv: "{{ wordpress__conf.db_name }}.*:ALL,GRANT"
    host: "%"
    login_user: "{{ wordpress__conf.db_admin_user }}"
    login_password: "{{ wordpress__conf.db_admin_password }}"
    login_host: "{{ wordpress__conf.db_host }}"

- name: MySQL/MariaDB db create
  mysql_db:
    name: "{{ wordpress__conf.db_name }}"
    login_user: "{{ wordpress__conf.db_admin_user }}"
    login_password: "{{ wordpress__conf.db_admin_password }}"
    login_host: "{{ wordpress__conf.db_host }}"

- name: Create apache service file
  template:
    src: vhost.conf
    dest: "/etc/apache2/sites-available/{{ wordpress__conf.hostname }}"
  notify: Reload apache2 service

- name: Create apache2 link service file
  file:
    path: "/etc/apache2/sites-enabled/{{ wordpress__conf.hostname }}.conf"
    src: "/etc/apache2/sites-available/{{ wordpress__conf.hostname }}"
    state: link
  notify: Reload apache2 service

- name: Create wordpress config file
  template:
    src: config-site.conf
    dest: "/etc/wordpress/config-{{ wordpress__conf.hostname }}.php"
